---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-json"
      - id: "check-shebang-scripts-are-executable"
      - id: "check-executables-have-shebangs"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "trailing-whitespace"
      - id: "check-merge-conflict"
      - id: "check-symlinks"
      - id: "check-toml"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "destroyed-symlinks"
      - id: "forbid-submodules"

  - repo: "https://github.com/golangci/golangci-lint"
    rev: "v1.64.8"
    hooks:
      - id: "golangci-lint-full"

  - repo: "https://github.com/koalaman/shellcheck-precommit"
    rev: "v0.11.0"
    hooks:
      - id: "shellcheck"

  - repo: "https://github.com/scop/pre-commit-shfmt"
    rev: "v3.8.0-1"
    hooks:
      - id: "shfmt-src"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.37.1"
    hooks:
      - id: "yamllint"

  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: "v0.45.0"
    hooks:
      - id: "markdownlint-fix"

  - repo: "https://github.com/rhysd/actionlint"
    rev: "v1.7.7"
    hooks:
      - id: "actionlint"

  - repo: "local"
    hooks:
      - id: "labdoc-generate-test-hook"
        name: "Test this repositories hook 'labdoc-generate'"
        language: "system"
        entry: "pre-commit try-repo --verbose --all-files ./ labdoc-generate"
        pass_filenames: false
...
