---
version: "3"

tasks:
  lint:
    cmds:
      - "pre-commit run --all-files"

  test:
    cmds:
      - "go test ./..."

  run:
    cmds:
      - "go run main.go {{ .CLI_ARGS }}"

  run-generate:
    cmds:
      - "go run main.go generate --repoUrl gitlab.com/erNail/labdoc {{ .CLI_ARGS }}"

  build:
    cmds:
      - "go build -o dist/"

  build-image:
    cmds:
      - "ko build --platform all --local"

  test-release-goreleaser:
    cmds:
      - "goreleaser release --snapshot --clean"

  test-release-semantic-release:
    cmds:
      - "semantic-release --dry-run"

  test-version-ldflags:
    cmds:
      - "go run -ldflags '-s -w -X github.com/erNail/labdoc/cmd.version=v1.2.3' main.go --version"

  test-github-actions:
    cmds:
      - "act"
...
