---
name: "CI/CD"

"on":
  push:

jobs:
  pre-commit:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Run linting, building, tests"
        run: "mise run pre-commit"

  determine-version-job:
    runs-on: "ubuntu-24.04"
    outputs:
      version: "${{ steps.get_version.outputs.version }}"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Run verscout next"
        id: "get_version"
        run: |
          VERSION=$(mise run verscout)
          if [ -z "$VERSION" ]; then
            exit 0
          fi
          if [ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]; then
            VERSION="${VERSION}-rc"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  release-job:
    runs-on: "ubuntu-24.04"
    needs:
      - "determine-version-job"
    if: "needs.determine-version-job.outputs.VERSION != ''"
    permissions:
      contents: "write"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Login to Docker Hub"
        uses: "docker/login-action@v4.1.0"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_LABDOC_GORELEASER_TOKEN }}"
      - name: "Generate release notes"
        run: "mise run changelog -- --tag ${{ needs.determine-version-job.outputs.VERSION }} --output release-notes.md"
      - name: "Create tag"
        run: "git tag ${{ needs.determine-version-job.outputs.VERSION }}"
      - name: "Run goreleaser"
        run: "goreleaser release --release-notes release-notes.md --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DOCKER_LABDOC_GORELEASER_TOKEN: "${{ secrets.DOCKER_LABDOC_GORELEASER_TOKEN }}"
          HOMEBREW_TAP_ERNAIL_GITHUB_TOKEN: "${{ secrets.HOMEBREW_TAP_ERNAIL_GITHUB_TOKEN }}"
...
